# Generated by Django 3.0.3 on 2020-02-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20200211_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_at',
            new_name='last_updated',
        ),
    ]
