# Generated by Django 3.0.3 on 2020-02-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20200211_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_created',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='user_created',
            new_name='author',
        ),
    ]
